services:
  wol-server:
    image: wol-unlock:0.1
    container_name: wol-server
    environment:
      - DISK_PASSWORD_FILE=/run/secrets/disk_password
    secrets:
      - disk_password
secrets:
  disk_password:
    file: secrets/disk_password